### PR TITLE
Update .gitmodules

### PR DESCRIPTION
**Pull request by phone-burner**
Update the broken link of GNU GRUB

### CODE REVIEW

**Comment by pbatard** [comment]
Can you explain the issue you trying to solve?

`git clone git://git.savannah.gnu.org/grub.git` works fine for me, and the URL in `.gitmodules` is meant to be used by `git` exclusively, in which case the `git://` protocol should be fine.

In other words, I will only apply this change if you can explain why you think it is needed...

**Comment by phone-burner** [comment]
IMG_20210602_204057
The old URL is inaccessible here .
Also, the URL on the official page of GNU GRUB has been updated. https://www.gnu.org/software/grub/grub-download.html

**Comment by pbatard** [comment]
> Also, the URL on the official page of GNU GRUB has been updated. https://www.gnu.org/software/grub/grub-download.html

Okay, fair enough.

**Comment by phone-burner** [comment]
IMG_20210602_205038

It seems that `git://` is not supported in this repository.

**Pull request closed without merging**
