### PR TITLE
add LOONGARCH64 compilation support

### PR DESCRIPTION
**Pull request by MarsDoge**
This is a RISC processor architecture - LOONGARCH64, and the upstream EDK2 and GRUB repositories have merged related architecture patches, embracing open source ...

### CODE REVIEW

**Comment by pbatard** [comment]
Thanks for this.

The builds cannot run however because it appears that you committed the grub submodule after you applied the `0001-GRUB-fixes.patch`, so you need to __revert__ your changes to the grub submodules and update your pull request so that it can be validated for builds. Then you can re-apply the patch in your local repository.

**Comment by pbatard** [comment]
Hmmm, it looks like `gcc-loongarch64-linux-gnu` is not yet available for ubuntu-latest (the base images used by GitHub for Linux builds) per: https://github.com/pbatard/efifs/actions/runs/6770275752/job/18398546553?pr=43#step:2:20

I also don't think the gnu-efi compilation for LOONGARCH64 will work, since we can't update to a newer version of gnu-efi, and the ones we use has no biding for LOONGARCH64, so the `linux_gcc_gnu-efi.yml` GitHub actions file you modified is most likely bound to fail, even if `gcc-loongarch64-linux-gnu` is available.

I guess we can drop support for gnu-efi/LOONGARCH64, but obviously, since the binaries I publish are build through GitHub actions, we're going to have to wait until Ubuntu adds `gcc-loongarch64-linux-gnu` to their standard packages before we can add support for it in EfiFs. Right now, it seems like [only binutils for LOONGARCH64 are available](https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=loongarch&searchon=names)...

**Comment by MarsDoge** [comment]
> Hmmm, it looks like `gcc-loongarch64-linux-gnu` is not yet available for ubuntu-latest (the base images used by GitHub for Linux builds) per: https://github.com/pbatard/efifs/actions/runs/6770275752/job/18398546553?pr=43#step:2:20
> 
> I also don't think the gnu-efi compilation for LOONGARCH64 will work, since we can't update to a newer version of gnu-efi, and the ones we use has no biding for LOONGARCH64, so the `linux_gcc_gnu-efi.yml` GitHub actions file you modified is most likely bound to fail, even if `gcc-loongarch64-linux-gnu` is available.
> 
> I guess we can drop support for gnu-efi/LOONGARCH64, but obviously, since the binaries I publish are build through GitHub actions, we're going to have to wait until Ubuntu adds `gcc-loongarch64-linux-gnu` to their standard packages before we can add support for it in EfiFs. Right now, it seems like [only binutils for LOONGARCH64 are available](https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=loongarch&searchon=names)...

Thank you very much for your reply. 
It is true that the latest ubuntu release version does not yet integrate the LoongArch compilation tool chain. 
Can I add efi support first?

**Comment by MarsDoge** [comment]
Looking forward to Ubuntu adds `gcc-loongarch64-linux-gnu` to their standard packages, I will request this PR again.

**Comment by pbatard** [comment]
Please hold on - I'm working on it. And yes, I will reference this PR and credit you when everything is finalized, but I first need to get everything working in GitHub Actions so that we don't get multiple commit references here, from commits that will be deleted.

**Comment by pbatard** [comment]
Okay, I should have the automated builds working now.

So, since Linux distros/GNU tools have been slow to add LoongArch64 support, and since a toolchain can be obtained from https://github.com/loongson/build-tools/releases/, we're going to use that toolchain for the builds.

I will try to produce a new release of EfiFs with the LoongArch64 drivers, but I want to update GRUB to latest and clean up a few more things before that, so it might be a little while before that happens.

Thanks again for this Pull Request.

**Comment by MarsDoge** [comment]
Thank you for the mergy! I completely understand the need to clean up a few more things before the release. Using the toolchain from the LoongArch build tools sounds like a good approach. I look forward to the new EfiFs release with LoongArch64 support, and I'll keep an eye out for any updates on GRUB as well.
﻿
Thanks again for your hard work on this! Let me know if there's anything I can do to assist further.

**Pull request closed without merging**
